global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.

scrape_configs:
  - job_name: "prometheus" # filtrar o crear jobs de monitoreo por servicio
    static_configs:
      - targets: ["prometheus:9090"] # nombre del servicio apuntando al puerto

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: "node_exporter"
    static_configs:
      - targets: ["node_exporter:9200"]

  - job_name: "app_example"
    static_configs:
      - targets: ["app_example:8080"]
    
